/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as PowerRouteImport } from './routes/power'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HomelabRouteImport } from './routes/homelab'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DockerRouteImport } from './routes/docker'
import { Route as CrontabRouteImport } from './routes/crontab'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRoute = PowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HomelabRoute = HomelabRouteImport.update({
  id: '/homelab',
  path: '/homelab',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerRoute = DockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => rootRouteImport,
} as any)
const CrontabRoute = CrontabRouteImport.update({
  id: '/crontab',
  path: '/crontab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crontab': typeof CrontabRoute
  '/docker': typeof DockerRoute
  '/files': typeof FilesRoute
  '/homelab': typeof HomelabRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/packages': typeof PackagesRoute
  '/ports': typeof PortsRoute
  '/power': typeof PowerRoute
  '/processes': typeof ProcessesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crontab': typeof CrontabRoute
  '/docker': typeof DockerRoute
  '/files': typeof FilesRoute
  '/homelab': typeof HomelabRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/packages': typeof PackagesRoute
  '/ports': typeof PortsRoute
  '/power': typeof PowerRoute
  '/processes': typeof ProcessesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crontab': typeof CrontabRoute
  '/docker': typeof DockerRoute
  '/files': typeof FilesRoute
  '/homelab': typeof HomelabRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/packages': typeof PackagesRoute
  '/ports': typeof PortsRoute
  '/power': typeof PowerRoute
  '/processes': typeof ProcessesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crontab'
    | '/docker'
    | '/files'
    | '/homelab'
    | '/logs'
    | '/network'
    | '/packages'
    | '/ports'
    | '/power'
    | '/processes'
    | '/services'
    | '/settings'
    | '/storage'
    | '/terminal'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crontab'
    | '/docker'
    | '/files'
    | '/homelab'
    | '/logs'
    | '/network'
    | '/packages'
    | '/ports'
    | '/power'
    | '/processes'
    | '/services'
    | '/settings'
    | '/storage'
    | '/terminal'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/crontab'
    | '/docker'
    | '/files'
    | '/homelab'
    | '/logs'
    | '/network'
    | '/packages'
    | '/ports'
    | '/power'
    | '/processes'
    | '/services'
    | '/settings'
    | '/storage'
    | '/terminal'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrontabRoute: typeof CrontabRoute
  DockerRoute: typeof DockerRoute
  FilesRoute: typeof FilesRoute
  HomelabRoute: typeof HomelabRoute
  LogsRoute: typeof LogsRoute
  NetworkRoute: typeof NetworkRoute
  PackagesRoute: typeof PackagesRoute
  PortsRoute: typeof PortsRoute
  PowerRoute: typeof PowerRoute
  ProcessesRoute: typeof ProcessesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  TerminalRoute: typeof TerminalRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homelab': {
      id: '/homelab'
      path: '/homelab'
      fullPath: '/homelab'
      preLoaderRoute: typeof HomelabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker': {
      id: '/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof DockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crontab': {
      id: '/crontab'
      path: '/crontab'
      fullPath: '/crontab'
      preLoaderRoute: typeof CrontabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrontabRoute: CrontabRoute,
  DockerRoute: DockerRoute,
  FilesRoute: FilesRoute,
  HomelabRoute: HomelabRoute,
  LogsRoute: LogsRoute,
  NetworkRoute: NetworkRoute,
  PackagesRoute: PackagesRoute,
  PortsRoute: PortsRoute,
  PowerRoute: PowerRoute,
  ProcessesRoute: ProcessesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  TerminalRoute: TerminalRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
